### ISSUE TITLE
Doesn't build with Python 3.12, imp module is deprecated

### ISSUE THREAD

**Issue by andreasbaumann** [libfirm/libfirm#35]
Building on Archlinux (from the libfirm-git AUR package), Python is 3.12.4:

```
GEN build/gen/ir/ir/gen_proj_names.h                                                
/data/INSTALL/libfirm-git/src/libfirm/scripts/filters.py:9: SyntaxWarning: invalid escape sequence '\s'                                                                 
  args = re.split('\s*\n\s*', string)                                               
Traceback (most recent call last):                                                  
  File "/data/INSTALL/libfirm-git/src/libfirm/./scripts/gen_ir.py", line 71, in <module>                                                                                
    main(sys.argv)                                                                  
  File "/data/INSTALL/libfirm-git/src/libfirm/./scripts/gen_ir.py", line 48, in main
    spec.loader.exec_module(module)                                                 
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module           
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed      
  File "/data/INSTALL/libfirm-git/src/libfirm/scripts/ir_spec.py", line 7, in <module>                                                                                  
    from irops import Node, abstract, op, Attribute, prepare_nodes                  
  File "/data/INSTALL/libfirm-git/src/libfirm/scripts/irops.py", line 4, in <module>
    import imp                                                                      
ModuleNotFoundError: No module named 'imp'                                          
make: *** [Makefile:140: build/gen/ir/ir/gen_proj_names.h] Error 1                  
```

**Comment by mtk2xfugaku** [comment]
I have made a pull request to fix this issue, you can try this [fork](https://github.com/mtk2xfugaku/libfirm) while it's not merged yet. This will fix both the syntax warning and the imp module error
